version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 791931779936.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t youtube .
      - docker tag youtube:latest 791931779936.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 791931779936.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
      - printf '[{"name":"myTask:2","imageUri":"%s"}]' 791931779936.dkr.ecr.us-east-1.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
